@ChessAnalytics_HostAddress = http://localhost:5062
@ChessAPI = https://api.chess.com/pub/player/nexin5/games

GET {{ChessAnalytics_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{ChessAPI}}/2026/08/
Accept: application/json
###

GET {{ChessAnalytics_HostAddress}}/ChessGame/
Accept: application/json
###

GET {{ChessAnalytics_HostAddress}}/ChessGame/alt/
Accept: application/json
###